### ISSUE TITLE
Build race condition when running dev:server and dev:client 

### ISSUE THREAD

**Issue by arrjayh** [gtg092x/another-ssr-boilerplate#4]
Hey!

Awesome job on this boilerplate. I've found your blog post and this repo to be very helpful.

I'm running into an issue getting hot reloading to work however. Is it that you need to run `npm run build` before you run `npm run dev`?

**Comment by gtg092x** [comment]
Thanks!

**Comment by hickokr** [comment]
Ah yes! That would help wouldn't it...

So, I've been manually kicking off `dev:server` and `dev:client` in two seperate tmux sessions (and supplying environment variables manually). When ever I make an edit to App.js those two scripts re-build the sources in parallel. This works well until the webpack-dev-server on the client tries to live-reload the page. In this case, where it live-reloads the page, it almost always 404's as the `dev:sever` script hasn't entirely finished rebuilding and re-launching the server.

I'm suspecting it might have something to do with not using npm-run-all but I do not understand `run-p` well enough to determine how it might build those two things in parallel with the right timings.

Thanks for the speedy response!
